# Generated by Django 2.0.3 on 2018-03-26 11:20

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
